# Generated by Django 3.2.6 on 2021-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_remove_code_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=10)),
                ('price_text', models.CharField(max_length=200)),
                ('desc_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='description',
            name='code',
        ),
        migrations.RemoveField(
            model_name='price',
            name='code',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
