# Generated by Django 3.2.6 on 2021-08-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_auto_20210831_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code_text',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_text',
            new_name='price',
        ),
    ]
