# Generated by Django 3.2.6 on 2021-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0004_auto_20210831_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isle',
            field=models.IntegerField(null=True),
        ),
    ]
