# Generated by Django 3.2.6 on 2021-09-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0005_product_isle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.IntegerField(default=1),
        ),
    ]
